Elimdeki tüm textlerden unique oan kelimeleri çekiyorum.(STEM VE LEMİTAZİNG YAPTIKTAN SONRA) bu bizim sözlükümüz oluyor.

Sonra her text için bu sözlüge göre hangi kelime ne kadar kullanıldı bir vektör oluşturuyorsun.Burdan en fazla kullanılan kelimelerden bir Inferance ile beraber sonucu almış oluyoruz.

Bu BOW yöntemin biraz daha fazla vektörü uzun olabilir bu dezavantaj olabilir.

Sparse Representation: Vektörün çogunun 0 olması demektir.

Kelimelerin anlamlarını tam olarak yakalayamayabilir.

In [3]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv(f'../spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2, stratify=df.spam)

In [17]:
X_train.shape

(4457,)

In [19]:
type(X_train)

pandas.core.series.Series

In [20]:
X_train[:4]

1509    Sounds like something that someone testing me ...
4140    Ever green quote ever told by Jerry in cartoon...
641     Well imma definitely need to restock before th...
5106      Ding me on ya break fassyole! Blacko from londn
Name: Message, dtype: object

In [21]:
y_test[:3]

4873    0
5264    0
5134    0
Name: spam, dtype: int64

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59316 stored elements and shape (4457, 7777)>

In [25]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7777))

In [29]:
v.get_feature_names_out()[1000:1050]

array(['anyhow', 'anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'aphex',
       'apnt', 'apo', 'apologetic', 'apologise', 'apologize', 'apology',
       'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'application', 'apply', 'applyed',
       'appointment', 'appreciate', 'appreciated', 'approaches',
       'approaching', 'appropriate', 'approve', 'approved', 'approx',
       'apps', 'appt', 'appy', 'april', 'aproach', 'aptitude', 'aquarius',
       'ar'], dtype=object)

In [30]:
v.get_feature_names_out().shape

(7777,)

In [32]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [34]:
v.vocabulary_ #Karşısındakiler positionlarıdır.

{'sounds': 6380,
 'like': 4129,
 'something': 6344,
 'that': 6840,
 'someone': 6338,
 'testing': 6809,
 'me': 4422,
 'would': 7642,
 'sayy': 5971,
 'ever': 2677,
 'green': 3250,
 'quote': 5571,
 'told': 6984,
 'by': 1598,
 'jerry': 3828,
 'in': 3660,
 'cartoon': 1680,
 'person': 5195,
 'who': 7528,
 'irritates': 3763,
 'always': 936,
 'is': 3767,
 'the': 6843,
 'one': 4968,
 'loves': 4254,
 'vry': 7368,
 'much': 4656,
 'but': 1583,
 'fails': 2767,
 'to': 6967,
 'express': 2739,
 'it': 3778,
 'gud': 3277,
 'nyt': 4901,
 'well': 7489,
 'imma': 3643,
 'definitely': 2232,
 'need': 4754,
 'restock': 5788,
 'before': 1304,
 'thanksgiving': 6834,
 'll': 4179,
 'let': 4103,
 'you': 7736,
 'know': 3973,
 'when': 7515,
 'out': 5038,
 'ding': 2332,
 'on': 4962,
 'ya': 7697,
 'break': 1493,
 'fassyole': 2792,
 'blacko': 1377,
 'from': 3026,
 'londn': 4206,
 'wait': 7390,
 'will': 7550,
 'come': 1915,
 'lt': 4269,
 'gt': 3272,
 'min': 4500,
 'orange': 5009,
 'customer': 2135,
 'may': 4414,
 'now': 

In [36]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7777,))

In [ ]:
np.where(X_train_np[0]!=0)

(array([4129, 4422, 5971, 6338, 6344, 6380, 6809, 6840, 7642]),)

In [43]:
X_train_np[0][4129]

np.int64(1)

In [42]:
X_train[:4][1509]

'Sounds like something that someone testing me would sayy'

In [44]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [45]:
x_test_cv = v.transform(X_test)

In [48]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.95      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [49]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [50]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [51]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.95      0.96       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

